### ISSUE TITLE
Variable length of Quiz Code

### ISSUE THREAD

**Issue by timeisthelimit** [neces/Industrial-Project-Team-9#101]
A non-uniform length Quiz Code may lead to unnecessary confusion when players receive a code with an uncommon number of digits (other than 6). Quiz Code seems to range from 0 to 999,999 (1 in length to 6 in length) though a 6 digit length Quiz Code is most likely (range: 100,000-999,999. ~10x more likely than codes of length 1-5)

**Comment by cammy2404** [comment]
Did you look at the code where it generates a new Quiz Code?

newSessionId = (rand.Next(899999) + 100000)

This is what the code actually is. It makes sure that the lowest number possible is 6 digits long and then generates a random number within a range that means it will never exceed 6 digits either.

This is already in place and has been for almost 2 weeks.
